# Generated by Django 3.2.9 on 2021-11-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking_main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rooms",
            name="available",
            field=models.BooleanField(default=True),
        ),
    ]
