# Generated by Django 3.2.9 on 2021-11-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking_main", "0002_rooms_available"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("room", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="booking_main.rooms")),
            ],
            options={
                "unique_together": {("date", "room")},
            },
        ),
    ]
