# Generated by Django 3.2.9 on 2021-11-13 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("booking_main", "0004_reservation_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="reservations", to="booking_main.rooms"
            ),
        ),
    ]
