# Generated by Django 3.2.9 on 2021-11-13 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking_main", "0005_alter_reservation_room"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reservation",
            new_name="Reservations",
        ),
    ]
